/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AboutEvent: typeof import('./src/components/aboutEvent.vue')['default']
    BodyPage: typeof import('./src/components/bodyPage.vue')['default']
    Button: typeof import('primevue/button')['default']
    CardsInfoMember: typeof import('./src/components/cardsInfoMember.vue')['default']
    Carousel: typeof import('primevue/carousel')['default']
    ContentPage: typeof import('./src/components/contentPage.vue')['default']
    DrawerMembersSaved: typeof import('./src/components/drawerMembersSaved.vue')['default']
    EventTime: typeof import('./src/components/eventTime.vue')['default']
    FooterPage: typeof import('./src/components/footerPage.vue')['default']
    FormItem: typeof import('./src/components/formItem.vue')['default']
    Galleria: typeof import('primevue/galleria')['default']
    HeadContent: typeof import('./src/components/headContent.vue')['default']
    HeaderMenu: typeof import('./src/components/headerMenu.vue')['default']
    IIcBaselineFacebook: typeof import('~icons/ic/baseline-facebook')['default']
    ILineiconsInstagramOriginal: typeof import('~icons/lineicons/instagram-original')['default']
    IMaterialSymbolsCalendarMonth: typeof import('~icons/material-symbols/calendar-month')['default']
    IMaterialSymbolsFileMap: typeof import('~icons/material-symbols/file-map')['default']
    IMdiGithub: typeof import('~icons/mdi/github')['default']
    ITablerClockHour5: typeof import('~icons/tabler/clock-hour5')['default']
    LocationEvent: typeof import('./src/components/locationEvent.vue')['default']
    NotFoundView: typeof import('./src/components/NotFoundView.vue')['default']
    PayEventView: typeof import('./src/components/payEventView.vue')['default']
    RegisterMembers: typeof import('./src/components/registerMembers.vue')['default']
    RegistersCard: typeof import('./src/components/registersCard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TeamContent: typeof import('./src/components/teamContent.vue')['default']
    TimerToEvent: typeof import('./src/components/timerToEvent.vue')['default']
    Toast: typeof import('primevue/toast')['default']
    ViewPaymentMethods: typeof import('./src/components/viewPaymentMethods.vue')['default']
  }
}
